matrix:
  include:
    - node_js: node
      language: node_js
      script: npm run test:cover
      cache:
        directories:
          - node_modules
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - r: oldrel
      language: r
      cache: packages
    - r: release
      language: r
      cache: packages
      after_success:
        - Rscript -e 'covr::codecov()'
