matrix:
  include:
    - node_js: node
      language: node_js
      script: npm run test:cover
      cache:
        directories:
          - node_modules
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - r: oldrel
      language: r
      cache: packages
    - r: release
      language: r
      cache: packages
      after_success:
        - Rscript -e 'covr::codecov()'
        - R CMD INSTALL ${PKG_TARBALL}
        - >
          Rscript -e 'for (f in list.files("inst/examples", pattern = ".Rmd", full.names = TRUE, recursive = TRUE))
            rmarkdown::render(f, encoding = "UTF-8")'
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
